name: build-and-test
on: [push, pull_request]
env:
  MAKEFLAGS: "-j 2"
  OS_NAME: "linux"
jobs:

  gcc-4_8:
    runs-on: "ubuntu-16.04"
    env:
      MATRIX_EVAL: "CONFIG=gcc && CC=gcc-4.8 && CXX=g++-4.8"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
            ~/.local-bin 
          key: "gcc-4_8"
      - run: |
          sudo apt install          \
            g++-4.8                 \
            gperf                   \
            build-essential         \
            bison                   \
            flex                    \
            libreadline-dev         \
            gawk                    \
            tcl-dev                 \
            libffi-dev              \
            git                     \
            graphviz                \
            xdot                    \
            pkg-config              \
            python                  \
            python3                 \
            libboost-system-dev     \
            libboost-python-dev     \
            libboost-filesystem-dev \
            zlib1g-dev
      - run: bash .github/scripts/setup.sh
      - run: bash .github/scripts/build-and-test.sh
      - if: success()
        run: bash .github/scripts/deploy-after-success.sh

  gcc-9:
    runs-on: "ubuntu-16.04"
    env:
      MATRIX_EVAL: "CONFIG=gcc && CC=gcc-9 && CXX=g++-9"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
            ~/.local-bin 
          key: "gcc-9"
      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - run: |
          sudo apt install          \
            g++-9                   \
            gperf                   \
            build-essential         \
            bison                   \
            flex                    \
            libreadline-dev         \
            gawk                    \
            tcl-dev                 \
            libffi-dev              \
            git                     \
            graphviz                \
            xdot                    \
            pkg-config              \
            python                  \
            python3                 \
            libboost-system-dev     \
            libboost-python-dev     \
            libboost-filesystem-dev \
            zlib1g-dev
      - run: bash .github/scripts/setup.sh
      - run: bash .github/scripts/build-and-test.sh
      - if: success()
        run: bash .github/scripts/deploy-after-success.sh

  clang-3_8:
    runs-on: "ubuntu-16.04"
    env:
      MATRIX_EVAL: "CONFIG=clang && CC=clang-3.8 && CXX=clang++-3.8"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
            ~/.local-bin 
          key: "clang-3_8"
      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - uses: myci-actions/add-deb-repo@4
        with:
          repo: deb [trusted=yes] http://apt.llvm.org/precise llvm-toolchain-precise-3.8 main
          repo-name: llvm-precise-3_8
      - run: |
          sudo apt install          \
            clang-3.8               \
            gperf                   \
            build-essential         \
            bison                   \
            flex                    \
            libreadline-dev         \
            gawk                    \
            tcl-dev                 \
            libffi-dev              \
            git                     \
            graphviz                \
            xdot                    \
            pkg-config              \
            python                  \
            python3                 \
            libboost-system-dev     \
            libboost-python-dev     \
            libboost-filesystem-dev \
            zlib1g-dev
      - run: bash .github/scripts/setup.sh
      - run: bash .github/scripts/build-and-test.sh
      - if: success()
        run: bash .github/scripts/deploy-after-success.sh

  # Clang which ships on Trusty Linux
  clang-8:
    runs-on: "ubuntu-16.04"
    env:
      MATRIX_EVAL: "CONFIG=clang && CC=clang-8 && CXX=clang++-8"
    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v2
        with:
          path: |
            ~/.ccache
            ~/.local-bin 
          key: "clang-8"
      - run: sudo add-apt-repository ppa:ubuntu-toolchain-r/test
      - uses: myci-actions/add-deb-repo@4
        with:
          repo: deb http://apt.llvm.org/xenial llvm-toolchain-xenial-8 main
          repo-name: llvm-xenial-8
      - run: |
          sudo apt install          \
            clang-8                 \
            gperf                   \
            build-essential         \
            bison                   \
            flex                    \
            libreadline-dev         \
            gawk                    \
            tcl-dev                 \
            libffi-dev              \
            git                     \
            graphviz                \
            xdot                    \
            pkg-config              \
            python                  \
            python3                 \
            libboost-system-dev     \
            libboost-python-dev     \
            libboost-filesystem-dev \
            zlib1g-dev
      - run: bash .github/scripts/setup.sh
      - run: bash .github/scripts/build-and-test.sh
      - if: success()
        run: bash .github/scripts/deploy-after-success.sh
