name: 'main'

on:
  push:
    branches:
      - uhdm-yosys-equiv-check

jobs:

  build-binaries:
    runs-on: ubuntu-latest
    env:
      CC: gcc-9
      CXX: g++-9

    steps:

    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Build binaries
      run: |
        ./build_binaries.sh
        # By default actions/upload-artifact@v2 do not preserve file permissions
        # tar directory to workaround this issue
        # See https://github.com/actions/upload-artifact/issues/38
        tar -cvf binaries.tar image

    - name: Upload binaries
      uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: binaries.tar

  yosys-equiv-ibex:
    runs-on: ubuntu-latest
    needs: [build-binaries]
    strategy:
      matrix:
        IBEX_MODULE:
          - ibex_alu.sv
          - ibex_branch_predict.sv
          - ibex_compressed_decoder.sv
          - ibex_controller.sv
          - ibex_core.sv
          - ibex_core_tracing.sv
          - ibex_counter.sv
          - ibex_cs_registers.sv
          - ibex_csr.sv
          - ibex_decoder.sv
          - ibex_dummy_instr.sv
          - ibex_ex_block.sv
          - ibex_fetch_fifo.sv
          - ibex_icache.sv
          - ibex_id_stage.sv
          - ibex_if_stage.sv
          - ibex_load_store_unit.sv
          - ibex_multdiv_fast.sv
          - ibex_multdiv_slow.sv
          - ibex_pmp.sv
          - ibex_prefetch_buffer.sv
          - ibex_register_file_ff.sv
          - ibex_register_file_fpga.sv
          - ibex_register_file_latch.sv
          - ibex_tracer.sv
          - ibex_wb_stage.sv
      fail-fast:
        false
    env:
      CC: gcc-9
      CXX: g++-9
      GIT_HTTP_LOW_SPEED_LIMIT: 1
      GIT_HTTP_LOW_SPEED_TIME: 600

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt install -y g++-9 build-essential cmake tclsh ant default-jre swig google-perftools libgoogle-perftools-dev python3 python3-dev uuid uuid-dev tcl-dev flex libfl-dev

    - uses: actions/checkout@v2
      with:
        submodules: recursive
        fetch-depth: 1

    - uses: actions/setup-python@v2
      with:
         python-version: '3.7'

    - name: Download binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries

    # See https://github.com/actions/upload-artifact/issues/38
    - name: Extract
      run: tar -xf binaries.tar

    - name: Build & Test (yosys)
      run: ./equiv_ibex.sh ${{ matrix.IBEX_MODULE }}
